In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import os
from pathlib import Path
import uuid

In [6]:
print(os.getcwd())
df = pd.read_csv('../../data/en/metadata.csv')
print(df.shape)

cv_path = os.path.join(os.getcwd(), '../../data', 'en', 'clips')

cv_list = os.listdir(cv_path)

df = df[df['path'].isin(cv_list)]
print(df.shape)

/root/master_thesis/thesis_multi_speaker_asr/src/multi_speaker_asr
(45737, 11)
(45737, 11)

In [8]:
print(df.columns)
df = df.drop(df.columns[[0]], axis=1)
print(df.columns)

Index(['Unnamed: 0', 'client_id', 'path', 'sentence_id', 'sentence', 'age',
       'gender', 'accents', 'locale', 'clip', 'duration[ms]'],
      dtype='str')
Index(['client_id', 'path', 'sentence_id', 'sentence', 'age', 'gender',
       'accents', 'locale', 'clip', 'duration[ms]'],
      dtype='str')

In [9]:
print(df.shape)

df['uuid'] = [str(uuid.uuid4()) for _ in range(len(df))]
df.to_csv('metadata.csv', index=False)

(45737, 10)

In [ ]:
import matplotlib.pyplot as plt

age_order = [
    'teens', 'twenties', 'thirties', 'fourties',
    'fifties', 'sixties', 'seventies',
    'eighties', 'nineties'
]
age_dist = df['age'].value_counts(normalize=True).reindex(age_order)
gender_dist = df['gender'].value_counts(normalize=True)

top_accents = df['accents'].value_counts().head(10)
accents_dist = top_accents / top_accents.sum()

# --- Plot grid ---
fig, axes = plt.subplots(3, 1, figsize=(8, 12))

# Age
axes[0].bar(range(len(age_dist)), age_dist.values)
axes[0].set_title("Age distribution")
axes[0].set_xlabel("Age bucket")
axes[0].set_ylabel("Proportion")
axes[0].set_xticks(range(len(age_dist)))
axes[0].set_xticklabels(age_dist.index, rotation=45)

# Gender
axes[1].bar(gender_dist.index, gender_dist.values)
axes[1].set_title("Gender distribution")
axes[1].set_xlabel("Gender")
axes[1].set_xticks(range(len(gender_dist)))
axes[1].set_xticklabels(gender_dist.index, rotation=45)
axes[1].set_ylabel("Proportion")

# Accent (top 10)
axes[2].bar(range(len(accents_dist)), accents_dist.values)
axes[2].set_title("Top 10 accents (normalized)")
axes[2].set_xlabel("Accent")
axes[2].set_ylabel("Proportion")
axes[2].set_xticks(range(len(accents_dist)))
axes[2].set_xticklabels(accents_dist.index, rotation=90)

plt.tight_layout()
plt.show()

In [1]:
import pandas as pd
import uuid
import os
import shutil
import datacollective
from dotenv import load_dotenv

In [2]:
df_duration = pd.read_csv('/root/master_thesis/thesis_multi_speaker_asr/data/commonvoice-en/cv-corpus-25.0-2026-03-09/en/clip_durations.tsv', sep='\t')
df_test = pd.read_csv('/root/master_thesis/thesis_multi_speaker_asr/data/commonvoice-en/cv-corpus-25.0-2026-03-09/en/test.tsv', sep='\t')

In [3]:
cols = ['client_id', 'path', 'sentence_id', 'sentence',
        'age', 'gender', 'accents']

for col in cols:
    missing = df_test[col].isna().mean()
    print(f"{col}: {missing:.2%} missing")

client_id: 0.00% missing
path: 0.00% missing
sentence_id: 0.00% missing
sentence: 0.00% missing
age: 84.31% missing
gender: 86.05% missing
accents: 80.88% missing

In [4]:
# Clip duration csv:
df_duration = df_duration.rename(columns={'clip': 'path', 'duration[ms]': 'duration'}) # change column names to match test split naming convention
# Test split csv:
print(df_test.shape)
print(df_test.columns)

# Drop NaN values:
df_test = df_test.dropna(subset=['client_id', 'path', 'sentence_id', 'sentence'])
print(df_test.shape)

# Remove whitespaces, if any:
df_test['path'] = df_test['path'].str.strip()

# Drop some columns:
df_test = df_test.drop(['sentence_domain', 'up_votes', 'down_votes', 'variant', 'locale', 'segment'], axis=1)

# Add unique id to each row:
df_test['id'] = [str(uuid.uuid4()) for _ in range(len(df_test))]
print(df_test.shape)

# Add clip duration column:
df_test = df_test.merge(df_duration, on='path')
print(df_test.shape)

# Write to metdata.csv file:
df_test.to_csv('metadata.csv', index=False)

(16398, 13)
Index(['client_id', 'path', 'sentence_id', 'sentence', 'sentence_domain',
       'up_votes', 'down_votes', 'age', 'gender', 'accents', 'variant',
       'locale', 'segment'],
      dtype='str')
(16398, 13)
(16398, 8)
(16398, 9)

In [5]:
# Calculate total duration for the test split:
milliseconds = df_test['duration'].sum()

total_seconds = milliseconds // 1000
hours = total_seconds // 3600
minutes = (total_seconds % 3600) // 60
seconds = total_seconds % 60
time = '%02d:%02d:%02d'%(hours, minutes, seconds)
print(time)

27:09:57

In [7]:
# Filter the audio files in clips folder to contain the ones only present in the test split:
local_path = '/root/master_thesis/thesis_multi_speaker_asr/data/clips'
data_path = '/root/master_thesis/thesis_multi_speaker_asr/data/commonvoice-en/cv-corpus-25.0-2026-03-09/en/clips'
clips = os.listdir(data_path)
print(f'Number of clips in folder: {len(clips)}')

test_files = set(df_test['path'])

for item in clips:
    if item in test_files:
        shutil.copy(
            src=os.path.join(data_path, item),
            dst=local_path
        )


clips_test = os.listdir(local_path)
print(f'Number of clips in new folder: {len(clips_test)}')

Number of clips in folder: 2574404
Number of clips in new folder: 16398

In [7]:
df = pd.read_csv('/root/master_thesis/thesis_multi_speaker_asr/data/CORAAL/ATL_metadata_2020.05.txt', sep="\t")
df.to_csv('/root/master_thesis/thesis_multi_speaker_asr/data/CORAAL/metadata.csv', index=False)
df.head()

,CORAAL.Sub,Version.Created,Version.Modified,CORAAL.Spkr,CORAAL.File,Audio.Folder,Tarball,Primary.Spkr,SLAAP.Collection,SLAAP.Spkr,...,Bit.Rate,Sampling.Rate,Source.Device,Dig.Sampling.Rate,Dig.Bit.Rate,Dig.Channels,CORAAL.Length.of.Transcript,CORAAL.Word.Count,Is.Misc.Tier,Notes
0,ATL,v.2020.05,NaN,ATL_se0_ag2_f_01,ATL_se0_ag2_f_01_1,ATL_wav_part03,ATL_audio_part03_2020.05.tar.gz,yes,atl,atl001,...,16 bit,44.1 kHz,NaN,44.1 khz,16 bit,Mono,2339.8,6881,NaN,NaN
1,ATL,v.2020.05,NaN,ATL_se0_ag2_m_01,ATL_se0_ag2_m_01_1,ATL_wav_part04,ATL_audio_part04_2020.05.tar.gz,yes,atl,atl002,...,16 bit,44.1 kHz,NaN,44.1 khz,16 bit,Mono,2440.6,7166,NaN,NaN
2,ATL,v.2020.05,NaN,ATL_se0_ag2_f_02,ATL_se0_ag2_f_02_1,ATL_wav_part03,ATL_audio_part03_2020.05.tar.gz,yes,atl,atl003,...,16 bit,44.1 kHz,NaN,44.1 khz,16 bit,Mono,2497.4,5252,yes,NaN
3,ATL,v.2020.05,NaN,ATL_se0_ag1_m_01,ATL_se0_ag1_m_01_1,ATL_wav_part01,ATL_audio_part01_2020.05.tar.gz,yes,atl,atl004,...,16 bit,44.1 kHz,NaN,44.1 khz,16 bit,Mono,2755.3,7223,NaN,NaN
4,ATL,v.2020.05,NaN,ATL_se0_ag1_f_01,ATL_se0_ag1_f_01_1,ATL_wav_part01,ATL_audio_part01_2020.05.tar.gz,yes,atl,atl005,...,16 bit,44.1 kHz,NaN,44.1 khz,16 bit,Mono,1862.0,4586,NaN,NaN

In [13]:
print(df['CORAAL.File'].iloc[0])

ATL_se0_ag2_f_01_1

In [29]:
import librosa

audio, sr = librosa.load(path='/root/master_thesis/thesis_multi_speaker_asr/data/CORAAL/ATL_se0_ag2_m_03_1.wav')
print(librosa.get_duration(y=audio, sr=sr))


df = pd.read_csv('/root/master_thesis/thesis_multi_speaker_asr/data/CORAAL/metadata.csv')
df_2 = pd.DataFrame()
paths = []
ids = []
files = []
for i, row in df.iterrows():
    file = row['CORAAL.File']
    audio_path = file + '.wav'
    paths.append(audio_path)
    files.append(file)
    id = str(uuid.uuid4())
    ids.append(id)

df_2['CORAAL.File'] = files
df_2['path'] = paths
df_2['id'] = ids
df_2.head()

2889.499909297052

,CORAAL.File,path,id
0,ATL_se0_ag2_f_01_1,ATL_se0_ag2_f_01_1.wav,ccfe847f-dff7-41b1-96da-db13f229df73
1,ATL_se0_ag2_m_01_1,ATL_se0_ag2_m_01_1.wav,d3121dd6-4ab1-4fbb-b680-163196558ea6
2,ATL_se0_ag2_f_02_1,ATL_se0_ag2_f_02_1.wav,a9348157-e506-4da8-94b6-615ba3096a14
3,ATL_se0_ag1_m_01_1,ATL_se0_ag1_m_01_1.wav,6be8e426-4757-4672-ae02-76ab69cc7caf
4,ATL_se0_ag1_f_01_1,ATL_se0_ag1_f_01_1.wav,3fe519d3-5a20-4b95-8459-b72fef046216

In [30]:
merged = df.merge(df_2, on='CORAAL.File')
merged.head()

,CORAAL.Sub,Version.Created,Version.Modified,CORAAL.Spkr,CORAAL.File,Audio.Folder,Tarball,Primary.Spkr,SLAAP.Collection,SLAAP.Spkr,...,Source.Device,Dig.Sampling.Rate,Dig.Bit.Rate,Dig.Channels,CORAAL.Length.of.Transcript,CORAAL.Word.Count,Is.Misc.Tier,Notes,path,id
0,ATL,v.2020.05,NaN,ATL_se0_ag2_f_01,ATL_se0_ag2_f_01_1,ATL_wav_part03,ATL_audio_part03_2020.05.tar.gz,yes,atl,atl001,...,NaN,44.1 khz,16 bit,Mono,2339.8,6881,NaN,NaN,ATL_se0_ag2_f_01_1.wav,ccfe847f-dff7-41b1-96da-db13f229df73
1,ATL,v.2020.05,NaN,ATL_se0_ag2_m_01,ATL_se0_ag2_m_01_1,ATL_wav_part04,ATL_audio_part04_2020.05.tar.gz,yes,atl,atl002,...,NaN,44.1 khz,16 bit,Mono,2440.6,7166,NaN,NaN,ATL_se0_ag2_m_01_1.wav,d3121dd6-4ab1-4fbb-b680-163196558ea6
2,ATL,v.2020.05,NaN,ATL_se0_ag2_f_02,ATL_se0_ag2_f_02_1,ATL_wav_part03,ATL_audio_part03_2020.05.tar.gz,yes,atl,atl003,...,NaN,44.1 khz,16 bit,Mono,2497.4,5252,yes,NaN,ATL_se0_ag2_f_02_1.wav,a9348157-e506-4da8-94b6-615ba3096a14
3,ATL,v.2020.05,NaN,ATL_se0_ag1_m_01,ATL_se0_ag1_m_01_1,ATL_wav_part01,ATL_audio_part01_2020.05.tar.gz,yes,atl,atl004,...,NaN,44.1 khz,16 bit,Mono,2755.3,7223,NaN,NaN,ATL_se0_ag1_m_01_1.wav,6be8e426-4757-4672-ae02-76ab69cc7caf
4,ATL,v.2020.05,NaN,ATL_se0_ag1_f_01,ATL_se0_ag1_f_01_1,ATL_wav_part01,ATL_audio_part01_2020.05.tar.gz,yes,atl,atl005,...,NaN,44.1 khz,16 bit,Mono,1862.0,4586,NaN,NaN,ATL_se0_ag1_f_01_1.wav,3fe519d3-5a20-4b95-8459-b72fef046216

# AMI Corpus:
Preprocess the subset of the AMI Meeting Corpus that I plan to use.

In [41]:
import pandas as pd
import numpy as np
import os
import json
import xml.etree.ElementTree as ET
from pathlib import Path
import re
from pydub import AudioSegment
import librosa

NITE = "http://nite.sourceforge.net/" # Global attribute used for ID in all xml files...

In [ ]:
resource_path = os.path.join('../../', 'data/amicorpus/metadata/corpusResources')

# meetings.xml:
meetings_root = ET.parse(os.path.join(resource_path, 'meetings.xml')).getroot()


speaker_rows = []

for meeting in meetings_root.findall(".//meeting"):
    meeting_id = meeting.attrib["observation"]

    for speaker in meeting.findall(".//speaker"):
        speaker_rows.append({
            "meeting_id": meeting_id
        })

speaker_map = pd.DataFrame(speaker_rows)

# participants.xml:
participants_root = ET.parse(os.path.join(resource_path, 'participants.xml')).getroot()

participants = []
for participant in participants_root.findall(".//participant"):
    participants.append(participant.attrib)

participants_df = pd.DataFrame(participants)
participants_df = participants_df.rename(columns={'{http://nite.sourceforge.net/}id': 'participant_id'})

In [43]:
print(speaker_map.shape)
speaker_map.head()

(682, 1)

  meeting_id
0    IS1000a
1    IS1000a
2    IS1000a
3    IS1000a
4    IS1000b

In [4]:
print(participants_df.shape)
participants_df.head()

(189, 5)

  participant_id sex age_at_collection native_language meeting
0         FEE005   F              20.0         English  ES2002
1         MEE006   M              25.0         English  ES2002
2         MEE007   M              21.0         English  ES2002
3         MEE008   M              27.0         English  ES2002
4         MEE009   M               NaN         English  ES2003

In [5]:
meeting_df = speaker_map.merge(
    participants_df,
    on='participant_id',
    how="left"
)

In [32]:
print(meeting_df.shape)
meeting_df.head(20)
meeting_df.to_csv('/root/master_thesis/thesis_multi_speaker_asr/data/amicorpus/meeting_metadata.csv', index=False)

(682, 8)

In [52]:
# Copy audio paths into the meeting_metadata.csv: 
audio_dir = os.path.join('../..', 'data/amicorpus/wav')
path_metadata3 = '/root/master_thesis/thesis_multi_speaker_asr/data/amicorpus/metadata_3.csv'
df = pd.read_csv(path_metadata3)

meeting_wav_map = {} # maps meetingID to the audio file path
for root, dirs, files in os.walk(audio_dir):
    print(f'Directories list: {dirs}')
    print(f'Files list: {files}')
    if not files:
        continue
    temp = files[0].split(sep='.', maxsplit=1)[0]
    print(f'File: {temp}')
    newPath = os.path.join(temp, files[0])
    print(f'New path: {newPath}')
    meeting_wav_map[temp] = newPath


df['path'] = ''
for i, row in df.iterrows():
    meeting_id = row['meeting_id']
    if meeting_id in meeting_wav_map.keys():
        df.at[i, 'path'] = meeting_wav_map[meeting_id]

df.to_csv('/root/master_thesis/thesis_multi_speaker_asr/data/amicorpus/metadata_4.csv', index=False)
df.head(20)

Directories list: ['ES2016b', 'ES2016a', 'ES2014b', 'ES2014d', 'ES2014a', 'ES2013c', 'ES2013d', 'ES2016d', 'ES2013a', 'ES2015d', 'ES2015a', 'ES2015c', 'ES2015b', 'ES2013b', 'ES2016c', 'ES2014c']
Files list: []
Directories list: []
Files list: ['ES2016b.Mix-Headset.wav']
File: ES2016b
New path: ES2016b/ES2016b.Mix-Headset.wav
Directories list: []
Files list: ['ES2016a.Mix-Headset.wav']
File: ES2016a
New path: ES2016a/ES2016a.Mix-Headset.wav
Directories list: []
Files list: ['ES2014b.Mix-Headset.wav']
File: ES2014b
New path: ES2014b/ES2014b.Mix-Headset.wav
Directories list: []
Files list: ['ES2014d.Mix-Headset.wav']
File: ES2014d
New path: ES2014d/ES2014d.Mix-Headset.wav
Directories list: []
Files list: ['ES2014a.Mix-Headset.wav']
File: ES2014a
New path: ES2014a/ES2014a.Mix-Headset.wav
Directories list: []
Files list: ['ES2013c.Mix-Headset.wav']
File: ES2013c
New path: ES2013c/ES2013c.Mix-Headset.wav
Directories list: []
Files list: ['ES2013d.Mix-Headset.wav']
File: ES2013d
New path: ES2013d/ES2013d.Mix-Headset.wav
Directories list: []
Files list: ['ES2016d.Mix-Headset.wav']
File: ES2016d
New path: ES2016d/ES2016d.Mix-Headset.wav
Directories list: []
Files list: ['ES2013a.Mix-Headset.wav']
File: ES2013a
New path: ES2013a/ES2013a.Mix-Headset.wav
Directories list: []
Files list: ['ES2015d.Mix-Headset.wav']
File: ES2015d
New path: ES2015d/ES2015d.Mix-Headset.wav
Directories list: []
Files list: ['ES2015a.Mix-Headset.wav']
File: ES2015a
New path: ES2015a/ES2015a.Mix-Headset.wav
Directories list: []
Files list: ['ES2015c.Mix-Headset.wav']
File: ES2015c
New path: ES2015c/ES2015c.Mix-Headset.wav
Directories list: []
Files list: ['ES2015b.Mix-Headset.wav']
File: ES2015b
New path: ES2015b/ES2015b.Mix-Headset.wav
Directories list: []
Files list: ['ES2013b.Mix-Headset.wav']
File: ES2013b
New path: ES2013b/ES2013b.Mix-Headset.wav
Directories list: []
Files list: ['ES2016c.Mix-Headset.wav']
File: ES2016c
New path: ES2016c/ES2016c.Mix-Headset.wav
Directories list: []
Files list: ['ES2014c.Mix-Headset.wav']
File: ES2014c
New path: ES2014c/ES2014c.Mix-Headset.wav

,meeting_id,text,path
0,ES2014a,"Right , sostart of the first meeting . Uh .Mm-...",ES2014a/ES2014a.Mix-Headset.wav
1,ES2014b,Right uh .So um .So where's the PowerPoint pre...,ES2014b/ES2014b.Mix-Headset.wav
2,ES2014c,Okay .Right .Conceptual design meeting . Right...,ES2014c/ES2014c.Mix-Headset.wav
3,ES2014d,"So is Why not save that .No , you'll ha have t...",ES2014d/ES2014d.Mix-Headset.wav
4,ES2015a,"Alright , that did nothing . Okay . Welcome to...",ES2015a/ES2015a.Mix-Headset.wav
5,ES2015b,Okay .Yeah . That's okay . That's okay .Okay ....,ES2015b/ES2015b.Mix-Headset.wav
6,ES2015c,Is everyone ready to start ? Okay . Great . We...,ES2015c/ES2015c.Mix-Headset.wav
7,ES2015d,"Okay . Here we go .Alright , the agenda for th...",ES2015d/ES2015d.Mix-Headset.wav
8,ES2016a,"Okay . Oh , that's not gonna work .Oh , alrigh...",ES2016a/ES2016a.Mix-Headset.wav
9,ES2016b,Oh .DuOkay .Hm .Thanks for coming to this meet...,ES2016b/ES2016b.Mix-Headset.wav
10,ES2016c,Okay ..Right .Okay .Alright . Is everyone here...,ES2016c/ES2016c.Mix-Headset.wav
11,ES2016d,Yep . Soon as Iget this .Okay . This is our la...,ES2016d/ES2016d.Mix-Headset.wav

In [7]:
rows = []
words_path = os.path.join('../../', 'data/amicorpus/metadata/words')

words = {}
word_order = []


for xml_file in Path(words_path).glob("ES201[4-6]*.words.xml"):
    root = ET.parse(xml_file).getroot()

    meeting_id = xml_file.stem.split(".")[0]
    channel = xml_file.stem.split(".")[1]

    for word in root:
        w_id = word.attrib.get(f"{{{NITE}}}id")
        words[w_id] = {
            "start": float(word.attrib.get("starttime", "nan")),
            "end": float(word.attrib.get("endtime", "nan")),
            "word": word.text if word.text else 'NaN'
        }

        rows.append({
            "meeting_id": meeting_id,
            "channel": channel,
            "word_id": w_id,
            "start": float(word.attrib.get("starttime", "nan")),
            "end": float(word.attrib.get("endtime", "nan")),
            "word": word.text
        })

        word_order.append(w_id)

word_pos = {wid: i for i, wid in enumerate(word_order)}
transcripts_df = pd.DataFrame(rows)

In [11]:
rows = []
words_path = os.path.join('../../', 'data/amicorpus/metadata/segments')
utterances = []

for xml_file in Path(words_path).glob("ES201[4-6]*.segments.xml"):
    seg_root = ET.parse(xml_file).getroot()

    for seg in seg_root.findall('.//segment'):
        child = seg.find('.//{*}child')
        if child is None:
            continue

        ref = child.attrib['href']
        
        info = ref.split('#')[0]
        meeting_id = info.split('.')[0]
        channel = info.split('.')[1]

        word_ids = ref.split('#')[1]
        id_count = word_ids.count('id')
        print(id_count)
        matches = None
        if id_count > 1:
            # A range of words
            matches = re.search(r'id\(([^)]+)\)\.\.id\(([^)]+)\)', word_ids)
        else:
            # A single word
            matches = re.search(r'id\(([^)]+)\)', word_ids)

        word_group = [group for group in matches.groups()]
        utter_words = []
        if len(word_group) > 1:
            start = word_pos[word_group[0]]
            end = word_pos[word_group[1]]
            utter_words = word_order[start:end + 1]
            print(f'Start: {start}, End: {end}, Words: {utter_words}')
        else:
            start = word_pos[word_group[0]]
            utter_words = word_order[start:start + 1]
            print(f'Start: {start}, Words: {utter_words}')
        
        segment_utterance = ' '.join(words[id]['word'] for id in utter_words if words[id] and words[id]['word'] is not 'NaN')

        utterances.append({
        "segment_id": seg.attrib.get(f"{{{NITE}}}id"),
        "start": float(seg.attrib["transcriber_start"]),
        "end": float(seg.attrib["transcriber_end"]),
        "text": segment_utterance,
        'meeting_id': meeting_id,
        'channel': channel
    })

utterances_df = pd.DataFrame(utterances)

<>:42: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<>:42: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/tmp/ipykernel_50749/2004352216.py:42: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  segment_utterance = ' '.join(words[id]['word'] for id in utter_words if words[id] and words[id]['word'] is not 'NaN')

2
Start: 20022, End: 20037, Words: ['ES2015a.D.words0', 'ES2015a.D.words1', 'ES2015a.D.words2', 'ES2015a.D.words3', 'ES2015a.D.words4', 'ES2015a.D.words5', 'ES2015a.D.words6', 'ES2015a.D.words7', 'ES2015a.D.words8', 'ES2015a.D.words9', 'ES2015a.D.words10', 'ES2015a.D.words11', 'ES2015a.D.words12', 'ES2015a.D.words13', 'ES2015a.D.words14', 'ES2015a.D.words15']
1
Start: 20038, Words: ['ES2015a.D.words16']
1
Start: 20039, Words: ['ES2015a.D.words17']
1
Start: 20040, Words: ['ES2015a.D.words18']
1
Start: 20041, Words: ['ES2015a.D.words19']
2
Start: 20042, End: 20094, Words: ['ES2015a.D.words20', 'ES2015a.D.words21', 'ES2015a.D.words22', 'ES2015a.D.words23', 'ES2015a.D.words24', 'ES2015a.D.words25', 'ES2015a.D.words26', 'ES2015a.D.words27', 'ES2015a.D.words28', 'ES2015a.D.words29', 'ES2015a.D.words30', 'ES2015a.D.words31', 'ES2015a.D.words32', 'ES2015a.D.words33', 'ES2015a.D.words34', 'ES2015a.D.words35', 'ES2015a.D.words36', 'ES2015a.D.words37', 'ES2015a.D.words38', 'ES2015a.D.words39', 'ES2015a.D.words40', 'ES2015a.D.words41', 'ES2015a.D.words42', 'ES2015a.D.words43', 'ES2015a.D.words44', 'ES2015a.D.words45', 'ES2015a.D.words46', 'ES2015a.D.words47', 'ES2015a.D.words48', 'ES2015a.D.words49', 'ES2015a.D.words50', 'ES2015a.D.words51', 'ES2015a.D.words52', 'ES2015a.D.words53', 'ES2015a.D.words54', 'ES2015a.D.words55', 'ES2015a.D.words56', 'ES2015a.D.words57', 'ES2015a.D.words58', 'ES2015a.D.words59', 'ES2015a.D.words60', 'ES2015a.D.words61', 'ES2015a.D.words62', 'ES2015a.D.words63', 'ES2015a.D.words64', 'ES2015a.D.words65', 'ES2015a.D.words66', 'ES2015a.D.words67', 'ES2015a.D.words68', 'ES2015a.D.words69', 'ES2015a.D.words70', 'ES2015a.D.words71', 'ES2015a.D.words72']
1
Start: 20095, Words: ['ES2015a.D.words73']
1
Start: 20096, Words: ['ES2015a.D.words74']
2
Start: 20097, End: 20101, Words: ['ES2015a.D.words75', 'ES2015a.D.words76', 'ES2015a.D.words77', 'ES2015a.D.words78', 'ES2015a.D.words79']
1
Start: 20102, Words: ['ES2015a.D.words80']
1
Start: 20103, Words: ['ES2015a.D.words81']
1
Start: 20104, Words: ['ES2015a.D.words82']
1
Start: 20105, Words: ['ES2015a.D.words83']
1
Start: 20106, Words: ['ES2015a.D.words84']
2
Start: 20107, End: 20112, Words: ['ES2015a.D.words85', 'ES2015a.D.words86', 'ES2015a.D.words87', 'ES2015a.D.words88', 'ES2015a.D.words89', 'ES2015a.D.words90']
1
Start: 20113, Words: ['ES2015a.D.words91']
2
Start: 20114, End: 20123, Words: ['ES2015a.D.words92', 'ES2015a.D.words93', 'ES2015a.D.words94', 'ES2015a.D.words95', 'ES2015a.D.words96', 'ES2015a.D.words97', 'ES2015a.D.words98', 'ES2015a.D.words99', 'ES2015a.D.words100', 'ES2015a.D.words101']
2
Start: 20124, End: 20128, Words: ['ES2015a.D.words102', 'ES2015a.D.words103', 'ES2015a.D.words104', 'ES2015a.D.words105', 'ES2015a.D.words106']
2
Start: 20129, End: 20131, Words: ['ES2015a.D.words107', 'ES2015a.D.words108', 'ES2015a.D.words109']
1
Start: 20132, Words: ['ES2015a.D.words110']
1
Start: 20133, Words: ['ES2015a.D.words111']
2
Start: 20134, End: 20136, Words: ['ES2015a.D.words112', 'ES2015a.D.words113', 'ES2015a.D.words114']
2
Start: 20137, End: 20140, Words: ['ES2015a.D.words115', 'ES2015a.D.words116', 'ES2015a.D.words117', 'ES2015a.D.words118']
1
Start: 20141, Words: ['ES2015a.D.words119']
1
Start: 20142, Words: ['ES2015a.D.words120']
2
Start: 20143, End: 20231, Words: ['ES2015a.D.words121', 'ES2015a.D.words122', 'ES2015a.D.words123', 'ES2015a.D.words124', 'ES2015a.D.words125', 'ES2015a.D.words126', 'ES2015a.D.words127', 'ES2015a.D.words128', 'ES2015a.D.words129', 'ES2015a.D.words130', 'ES2015a.D.words131', 'ES2015a.D.words132', 'ES2015a.D.words133', 'ES2015a.D.words134', 'ES2015a.D.words135', 'ES2015a.D.words136', 'ES2015a.D.words137', 'ES2015a.D.words138', 'ES2015a.D.words139', 'ES2015a.D.words140', 'ES2015a.D.words141', 'ES2015a.D.words142', 'ES2015a.D.words143', 'ES2015a.D.words144', 'ES2015a.D.words145', 'ES2015a.D.words146', 'ES2015a.D.words147', 'ES2015a.D.words148', 'ES2015a.D.words149', 'ES2015a.D.words150', 'ES2015a.D.words151', 'ES2015a.D.words152', 'ES2015a.D.words153', 'ES2015a.D.words154', 'ES2015a.D.words155', 'ES2015a.D.words156', 'ES2015a.D.words157', 'ES2015a.D.words158', 'ES2015a.D.words159', 'ES2015a.D.words160', 'ES2015a.D.words161', 'ES2015a.D.words162', 'ES2015a.D.words163', 'ES2015a.D.words164', 'ES2015a.D.words165', 'ES2015a.D.words166', 'ES2015a.D.words167', 'ES2015a.D.words168', 'ES2015a.D.words169', 'ES2015a.D.words170', 'ES2015a.D.words171', 'ES2015a.D.words172', 'ES2015a.D.words173', 'ES2015a.D.words174', 'ES2015a.D.words175', 'ES2015a.D.words176', 'ES2015a.D.words177', 'ES2015a.D.words178', 'ES2015a.D.words179', 'ES2015a.D.words180', 'ES2015a.D.words181', 'ES2015a.D.words182', 'ES2015a.D.words183', 'ES2015a.D.words184', 'ES2015a.D.words185', 'ES2015a.D.words186', 'ES2015a.D.words187', 'ES2015a.D.words188', 'ES2015a.D.words189', 'ES2015a.D.words190', 'ES2015a.D.words191', 'ES2015a.D.words192', 'ES2015a.D.words193', 'ES2015a.D.words194', 'ES2015a.D.words195', 'ES2015a.D.words196', 'ES2015a.D.words197', 'ES2015a.D.words198', 'ES2015a.D.words199', 'ES2015a.D.words200', 'ES2015a.D.words201', 'ES2015a.D.words202', 'ES2015a.D.words203', 'ES2015a.D.words204', 'ES2015a.D.words205', 'ES2015a.D.words206', 'ES2015a.D.words207', 'ES2015a.D.words208', 'ES2015a.D.words209']
2
Start: 20232, End: 20297, Words: ['ES2015a.D.words210', 'ES2015a.D.words211', 'ES2015a.D.words212', 'ES2015a.D.words213', 'ES2015a.D.words214', 'ES2015a.D.words215', 'ES2015a.D.words216', 'ES2015a.D.words217', 'ES2015a.D.words218', 'ES2015a.D.words219', 'ES2015a.D.words220', 'ES2015a.D.words221', 'ES2015a.D.words222', 'ES2015a.D.words223', 'ES2015a.D.words224', 'ES2015a.D.words225', 'ES2015a.D.words226', 'ES2015a.D.words227', 'ES2015a.D.words228', 'ES2015a.D.words229', 'ES2015a.D.words230', 'ES2015a.D.words231', 'ES2015a.D.words232', 'ES2015a.D.words233', 'ES2015a.D.words234', 'ES2015a.D.words235', 'ES2015a.D.words236', 'ES2015a.D.words237', 'ES2015a.D.words238', 'ES2015a.D.words239', 'ES2015a.D.words240', 'ES2015a.D.words241', 'ES2015a.D.words242', 'ES2015a.D.words243', 'ES2015a.D.words244', 'ES2015a.D.words245', 'ES2015a.D.words246', 'ES2015a.D.words247', 'ES2015a.D.words248', 'ES2015a.D.words249', 'ES2015a.D.words250', 'ES2015a.D.words251', 'ES2015a.D.words252', 'ES2015a.D.words253', 'ES2015a.D.words254', 'ES2015a.D.words255', 'ES2015a.D.words256', 'ES2015a.D.words257', 'ES2015a.D.words258', 'ES2015a.D.words259', 'ES2015a.D.words260', 'ES2015a.D.words261', 'ES2015a.D.words262', 'ES2015a.D.words263', 'ES2015a.D.words264', 'ES2015a.D.words265', 'ES2015a.D.words266', 'ES2015a.D.words267', 'ES2015a.D.words268', 'ES2015a.D.words269', 'ES2015a.D.words270', 'ES2015a.D.words271', 'ES2015a.D.words272', 'ES2015a.D.words273', 'ES2015a.D.words274', 'ES2015a.D.words275']
2
Start: 20298, End: 20404, Words: ['ES2015a.D.words276', 'ES2015a.D.words277', 'ES2015a.D.words278', 'ES2015a.D.words279', 'ES2015a.D.words280', 'ES2015a.D.words281', 'ES2015a.D.words282', 'ES2015a.D.words283', 'ES2015a.D.words284', 'ES2015a.D.words285', 'ES2015a.D.words286', 'ES2015a.D.words287', 'ES2015a.D.words288', 'ES2015a.D.words289', 'ES2015a.D.words290', 'ES2015a.D.words291', 'ES2015a.D.words292', 'ES2015a.D.words293', 'ES2015a.D.words294', 'ES2015a.D.words295', 'ES2015a.D.words296', 'ES2015a.D.words297', 'ES2015a.D.words298', 'ES2015a.D.words299', 'ES2015a.D.words300', 'ES2015a.D.words301', 'ES2015a.D.words302', 'ES2015a.D.words303', 'ES2015a.D.words304', 'ES2015a.D.words305', 'ES2015a.D.words306', 'ES2015a.D.words307', 'ES2015a.D.words308', 'ES2015a.D.words309', 'ES2015a.D.words310', 'ES2015a.D.words311', 'ES2015a.D.words312', 'ES2015a.D.words313', 'ES2015a.D.words314', 'ES2015a.D.words315', 'ES2015a.D.words316', 'ES2015a.D.words317', 'ES2015a.D.words318', 'ES2015a.D.words319', 'ES2015a.D.words320', 'ES2015a.D.words321', 'ES2015a.D.words322', 'ES2015a.D.words323', 'ES2015a.D.words324', 'ES2015a.D.words325', 'ES2015a.D.words326', 'ES2015a.D.words327', 'ES2015a.D.words328', 'ES2015a.D.words329', 'ES2015a.D.words330', 'ES2015a.D.words331', 'ES2015a.D.words332', 'ES2015a.D.words333', 'ES2015a.D.words334', 'ES2015a.D.words335', 'ES2015a.D.words336', 'ES2015a.D.words337', 'ES2015a.D.words338', 'ES2015a.D.words339', 'ES2015a.D.words340', 'ES2015a.D.words341', 'ES2015a.D.words342', 'ES2015a.D.words343', 'ES2015a.D.words344', 'ES2015a.D.words345', 'ES2015a.D.words346', 'ES2015a.D.words347', 'ES2015a.D.words348', 'ES2015a.D.words349', 'ES2015a.D.words350', 'ES2015a.D.words351', 'ES2015a.D.words352', 'ES2015a.D.words353', 'ES2015a.D.words354', 'ES2015a.D.words355', 'ES2015a.D.words356', 'ES2015a.D.words357', 'ES2015a.D.words358', 'ES2015a.D.words359', 'ES2015a.D.words360', 'ES2015a.D.words361', 'ES2015a.D.words362', 'ES2015a.D.words363', 'ES2015a.D.words364', 'ES2015a.D.words365', 'ES2015a.D.words366', 'ES2015a.D.words367', 'ES2015a.D.words368', 'ES2015a.D.words369', 'ES2015a.D.words370', 'ES2015a.D.words371', 'ES2015a.D.words372', 'ES2015a.D.words373', 'ES2015a.D.words374', 'ES2015a.D.words375', 'ES2015a.D.words376', 'ES2015a.D.words377', 'ES2015a.D.words378', 'ES2015a.D.words379', 'ES2015a.D.words380', 'ES2015a.D.words381', 'ES2015a.D.words382']
2
Start: 20405, End: 20413, Words: ['ES2015a.D.words383', 'ES2015a.D.words384', 'ES2015a.D.words385', 'ES2015a.D.words386', 'ES2015a.D.words387', 'ES2015a.D.words388', 'ES2015a.D.words389', 'ES2015a.D.words390', 'ES2015a.D.words391']
2
Start: 20414, End: 20419, Words: ['ES2015a.D.words392', 'ES2015a.D.words393', 'ES2015a.D.words394', 'ES2015a.D.words395', 'ES2015a.D.words396', 'ES2015a.D.words397']
1
Start: 20420, Words: ['ES2015a.D.words398']
2
Start: 20421, End: 20434, Words: ['ES2015a.D.words399', 'ES2015a.D.words400', 'ES2015a.D.words401', 'ES2015a.D.words402', 'ES2015a.D.words403', 'ES2015a.D.words404', 'ES2015a.D.words405', 'ES2015a.D.words406', 'ES2015a.D.words407', 'ES2015a.D.words408', 'ES2015a.D.words409', 'ES2015a.D.words410', 'ES2015a.D.words411', 'ES2015a.D.words412']
2
Start: 20435, End: 20436, Words: ['ES2015a.D.words413', 'ES2015a.D.words414']
2
Start: 20437, End: 20452, Words: ['ES2015a.D.words415', 'ES2015a.D.words416', 'ES2015a.D.words417', 'ES2015a.D.words418', 'ES2015a.D.words419', 'ES2015a.D.words420', 'ES2015a.D.words421', 'ES2015a.D.words422', 'ES2015a.D.words423', 'ES2015a.D.words424', 'ES2015a.D.words425', 'ES2015a.D.words426', 'ES2015a.D.words427', 'ES2015a.D.words428', 'ES2015a.D.words429', 'ES2015a.D.words430']
1
Start: 20453, Words: ['ES2015a.D.words431']
2
Start: 20454, End: 20455, Words: ['ES2015a.D.words432', 'ES2015a.D.words433']
2
Start: 20456, End: 20457, Words: ['ES2015a.D.words434', 'ES2015a.D.words435']
2
Start: 20458, End: 20459, Words: ['ES2015a.D.words436', 'ES2015a.D.words437']
2
Start: 20460, End: 20505, Words: ['ES2015a.D.words438', 'ES2015a.D.words439', 'ES2015a.D.words440', 'ES2015a.D.words441', 'ES2015a.D.words442', 'ES2015a.D.words443', 'ES2015a.D.words444', 'ES2015a.D.words445', 'ES2015a.D.words446', 'ES2015a.D.words447', 'ES2015a.D.words448', 'ES2015a.D.words449', 'ES2015a.D.words450', 'ES2015a.D.words451', 'ES2015a.D.words452', 'ES2015a.D.words453', 'ES2015a.D.words454', 'ES2015a.D.words455', 'ES2015a.D.words456', 'ES2015a.D.words457', 'ES2015a.D.words458', 'ES2015a.D.words459', 'ES2015a.D.words460', 'ES2015a.D.words461', 'ES2015a.D.words462', 'ES2015a.D.words463', 'ES2015a.D.words464', 'ES2015a.D.words465', 'ES2015a.D.words466', 'ES2015a.D.words467', 'ES2015a.D.words468', 'ES2015a.D.words469', 'ES2015a.D.words470', 'ES2015a.D.words471', 'ES2015a.D.words472', 'ES2015a.D.words473', 'ES2015a.D.words474', 'ES2015a.D.words475', 'ES2015a.D.words476', 'ES2015a.D.words477', 'ES2015a.D.words478', 'ES2015a.D.words479', 'ES2015a.D.words480', 'ES2015a.D.words481', 'ES2015a.D.words482', 'ES2015a.D.words483']
1
Start: 20506, Words: ['ES2015a.D.words484']
2
Start: 20507, End: 20524, Words: ['ES2015a.D.words485', 'ES2015a.D.words486', 'ES2015a.D.words487', 'ES2015a.D.words488', 'ES2015a.D.words489', 'ES2015a.D.words490', 'ES2015a.D.words491', 'ES2015a.D.words492', 'ES2015a.D.words493', 'ES2015a.D.words494', 'ES2015a.D.words495', 'ES2015a.D.words496', 'ES2015a.D.words497', 'ES2015a.D.words498', 'ES2015a.D.words499', 'ES2015a.D.words500', 'ES2015a.D.words501', 'ES2015a.D.words502']
1
Start: 20525, Words: ['ES2015a.D.words503']
2
Start: 20526, End: 20527, Words: ['ES2015a.D.words504', 'ES2015a.D.words505']
2
Start: 20528, End: 20533, Words: ['ES2015a.D.words506', 'ES2015a.D.words507', 'ES2015a.D.words508', 'ES2015a.D.words509', 'ES2015a.D.words510', 'ES2015a.D.words511']
2
Start: 20534, End: 20537, Words: ['ES2015a.D.words512', 'ES2015a.D.words513', 'ES2015a.D.words514', 'ES2015a.D.words515']
1
Start: 18297, Words: ['ES2016d.A.words0']
2
Start: 18298, End: 18302, Words: ['ES2016d.A.words1', 'ES2016d.A.words2', 'ES2016d.A.words3', 'ES2016d.A.words4', 'ES2016d.A.words5']
2
Start: 18303, End: 18305, Words: ['ES2016d.A.words6', 'ES2016d.A.words7', 'ES2016d.A.words8']
2
Start: 18306, End: 18313, Words: ['ES2016d.A.words9', 'ES2016d.A.words10', 'ES2016d.A.words11', 'ES2016d.A.words12', 'ES2016d.A.words13', 'ES2016d.A.words14', 'ES2016d.A.words15', 'ES2016d.A.words16']
2
Start: 18314, End: 18381, Words: ['ES2016d.A.words17', 'ES2016d.A.words18', 'ES2016d.A.words19', 'ES2016d.A.words20', 'ES2016d.A.words21', 'ES2016d.A.words22', 'ES2016d.A.words23', 'ES2016d.A.words24', 'ES2016d.A.words25', 'ES2016d.A.words26', 'ES2016d.A.words27', 'ES2016d.A.words28', 'ES2016d.A.words29', 'ES2016d.A.words30', 'ES2016d.A.words31', 'ES2016d.A.words32', 'ES2016d.A.words33', 'ES2016d.A.words34', 'ES2016d.A.words35', 'ES2016d.A.words36', 'ES2016d.A.words37', 'ES2016d.A.words38', 'ES2016d.A.words39', 'ES2016d.A.words40', 'ES2016d.A.words41', 'ES2016d.A.words42', 'ES2016d.A.words43', 'ES2016d.A.words44', 'ES2016d.A.words45', 'ES2016d.A.words46', 'ES2016d.A.words47', 'ES2016d.A.words48', 'ES2016d.A.words49', 'ES2016d.A.words50', 'ES2016d.A.words51', 'ES2016d.A.words52', 'ES2016d.A.words53', 'ES2016d.A.words54', 'ES2016d.A.words55', 'ES2016d.A.words56', 'ES2016d.A.words57', 'ES2016d.A.words58', 'ES2016d.A.words59', 'ES2016d.A.words60', 'ES2016d.A.words61', 'ES2016d.A.words62', 'ES2016d.A.words63', 'ES2016d.A.words64', 'ES2016d.A.words65', 'ES2016d.A.words66', 'ES2016d.A.words67', 'ES2016d.A.words68', 'ES2016d.A.words69', 'ES2016d.A.words70', 'ES2016d.A.words71', 'ES2016d.A.words72', 'ES2016d.A.words73', 'ES2016d.A.words74', 'ES2016d.A.words75', 'ES2016d.A.words76', 'ES2016d.A.words77', 'ES2016d.A.words78', 'ES2016d.A.words79', 'ES2016d.A.words80', 'ES2016d.A.words81', 'ES2016d.A.words82', 'ES2016d.A.words83', 'ES2016d.A.words84']
2
Start: 18382, End: 18415, Words: ['ES2016d.A.words85', 'ES2016d.A.words86', 'ES2016d.A.words87', 'ES2016d.A.words88', 'ES2016d.A.words89', 'ES2016d.A.words90', 'ES2016d.A.words91', 'ES2016d.A.words92', 'ES2016d.A.words93', 'ES2016d.A.words94', 'ES2016d.A.words95', 'ES2016d.A.words96', 'ES2016d.A.words97', 'ES2016d.A.words98', 'ES2016d.A.words99', 'ES2016d.A.words100', 'ES2016d.A.words101', 'ES2016d.A.words102', 'ES2016d.A.words103', 'ES2016d.A.words104', 'ES2016d.A.words105', 'ES2016d.A.words106', 'ES2016d.A.words107', 'ES2016d.A.words108', 'ES2016d.A.words109', 'ES2016d.A.words110', 'ES2016d.A.words111', 'ES2016d.A.words112', 'ES2016d.A.words113', 'ES2016d.A.words114', 'ES2016d.A.words115', 'ES2016d.A.words116', 'ES2016d.A.words117', 'ES2016d.A.words118']
2
Start: 18416, End: 18467, Words: ['ES2016d.A.words119', 'ES2016d.A.words120', 'ES2016d.A.words121', 'ES2016d.A.words122', 'ES2016d.A.words123', 'ES2016d.A.words124', 'ES2016d.A.words125', 'ES2016d.A.words126', 'ES2016d.A.words127', 'ES2016d.A.words128', 'ES2016d.A.words129', 'ES2016d.A.words130', 'ES2016d.A.words131', 'ES2016d.A.words132', 'ES2016d.A.words133', 'ES2016d.A.words134', 'ES2016d.A.words135', 'ES2016d.A.words136', 'ES2016d.A.words137', 'ES2016d.A.words138', 'ES2016d.A.words139', 'ES2016d.A.words140', 'ES2016d.A.words141', 'ES2016d.A.words142', 'ES2016d.A.words143', 'ES2016d.A.words144', 'ES2016d.A.words145', 'ES2016d.A.words146', 'ES2016d.A.words147', 'ES2016d.A.words148', 'ES2016d.A.words149', 'ES2016d.A.words150', 'ES2016d.A.words151', 'ES2016d.A.words152', 'ES2016d.A.words153', 'ES2016d.A.words154', 'ES2016d.A.words155', 'ES2016d.A.words156', 'ES2016d.A.words157', 'ES2016d.A.words158', 'ES2016d.A.words159', 'ES2016d.A.words160', 'ES2016d.A.words161', 'ES2016d.A.words162', 'ES2016d.A.words163', 'ES2016d.A.words164', 'ES2016d.A.words165', 'ES2016d.A.words166', 'ES2016d.A.words167', 'ES2016d.A.words168', 'ES2016d.A.words169', 'ES2016d.A.words170']
2
Start: 18468, End: 18530, Words: ['ES2016d.A.words171', 'ES2016d.A.words172', 'ES2016d.A.words173', 'ES2016d.A.words174', 'ES2016d.A.words175', 'ES2016d.A.words176', 'ES2016d.A.words177', 'ES2016d.A.words178', 'ES2016d.A.words179', 'ES2016d.A.words180', 'ES2016d.A.words181', 'ES2016d.A.words182', 'ES2016d.A.words183', 'ES2016d.A.words184', 'ES2016d.A.words185', 'ES2016d.A.words186', 'ES2016d.A.words187', 'ES2016d.A.words188', 'ES2016d.A.words189', 'ES2016d.A.words190', 'ES2016d.A.words191', 'ES2016d.A.words192', 'ES2016d.A.words193', 'ES2016d.A.words194', 'ES2016d.A.words195', 'ES2016d.A.words196', 'ES2016d.A.words197', 'ES2016d.A.words198', 'ES2016d.A.words199', 'ES2016d.A.words200', 'ES2016d.A.words201', 'ES2016d.A.words202', 'ES2016d.A.words203', 'ES2016d.A.words204', 'ES2016d.A.words205', 'ES2016d.A.words206', 'ES2016d.A.words207', 'ES2016d.A.words208', 'ES2016d.A.words209', 'ES2016d.A.words210', 'ES2016d.A.words211', 'ES2016d.A.words212', 'ES2016d.A.words213', 'ES2016d.A.words214', 'ES2016d.A.words215', 'ES2016d.A.words216', 'ES2016d.A.words217', 'ES2016d.A.words218', 'ES2016d.A.words219', 'ES2016d.A.words220', 'ES2016d.A.words221', 'ES2016d.A.words222', 'ES2016d.A.words223', 'ES2016d.A.words224', 'ES2016d.A.words225', 'ES2016d.A.words226', 'ES2016d.A.words227', 'ES2016d.A.words228', 'ES2016d.A.words229', 'ES2016d.A.words230', 'ES2016d.A.words231', 'ES2016d.A.words232', 'ES2016d.A.words233']
2
Start: 18531, End: 18600, Words: ['ES2016d.A.words234', 'ES2016d.A.words235', 'ES2016d.A.words236', 'ES2016d.A.words237', 'ES2016d.A.words238', 'ES2016d.A.words239', 'ES2016d.A.words240', 'ES2016d.A.words241', 'ES2016d.A.words242', 'ES2016d.A.words243', 'ES2016d.A.words244', 'ES2016d.A.words245', 'ES2016d.A.words246', 'ES2016d.A.words247', 'ES2016d.A.words248', 'ES2016d.A.words249', 'ES2016d.A.words250', 'ES2016d.A.words251', 'ES2016d.A.words252', 'ES2016d.A.words253', 'ES2016d.A.words254', 'ES2016d.A.words255', 'ES2016d.A.words256', 'ES2016d.A.words257', 'ES2016d.A.words258', 'ES2016d.A.words259', 'ES2016d.A.words260', 'ES2016d.A.words261', 'ES2016d.A.words262', 'ES2016d.A.words263', 'ES2016d.A.words264', 'ES2016d.A.words265', 'ES2016d.A.words266', 'ES2016d.A.words267', 'ES2016d.A.words268', 'ES2016d.A.words269', 'ES2016d.A.words270', 'ES2016d.A.words271', 'ES2016d.A.words272', 'ES2016d.A.words273', 'ES2016d.A.words274', 'ES2016d.A.words275', 'ES2016d.A.words276', 'ES2016d.A.words277', 'ES2016d.A.words278', 'ES2016d.A.words279', 'ES2016d.A.words280', 'ES2016d.A.words281', 'ES2016d.A.words282', 'ES2016d.A.words283', 'ES2016d.A.words284', 'ES2016d.A.words285', 'ES2016d.A.words286', 'ES2016d.A.words287', 'ES2016d.A.words288', 'ES2016d.A.words289', 'ES2016d.A.words290', 'ES2016d.A.words291', 'ES2016d.A.words292', 'ES2016d.A.words293', 'ES2016d.A.words294', 'ES2016d.A.words295', 'ES2016d.A.words296', 'ES2016d.A.words297', 'ES2016d.A.words298', 'ES2016d.A.words299', 'ES2016d.A.words300', 'ES2016d.A.words301', 'ES2016d.A.words302', 'ES2016d.A.words303']
2

In [49]:
transcripts_df = transcripts_df.merge(
    speaker_map,
    on=["meeting_id", "channel"],
    how="left"
)

transcripts_df = transcripts_df.merge(
    participants_df,
    on='participant_id',
    how="left"
)

In [52]:
transcripts_df.to_csv('/root/master_thesis/thesis_multi_speaker_asr/data/amicorpus/metadata.csv', index=False)

In [12]:
utterances_df = utterances_df.merge(
    speaker_map,
    on=["meeting_id", "channel"],
    how="left"
)

utterances_df = utterances_df.merge(
    participants_df,
    on='participant_id',
    how="left"
)

In [13]:
utterances_df.to_csv('/root/master_thesis/thesis_multi_speaker_asr/data/amicorpus/metadata2.csv', index=False)

In [24]:
path = '../../data/amicorpus'
amiDir = os.listdir(path=path)
print(amiDir)
durMap = {

}

for meet in amiDir:
    if meet == 'metadata':
        continue
    p = os.path.join(path, meet, 'audio')
    wavs = os.listdir(p)[0]
    audio, sr = librosa.load(os.path.join(p, wavs))
    dur = librosa.get_duration(y=audio, sr=sr)

    durMap[meet] = dur

total_dur = sum(durMap.values())
avg_dur = total_dur / len(durMap.keys())

print(total_dur)
print(durMap)
print(avg_dur)

['ES2016b', 'ES2016a', 'ES2014b', 'ES2014d', 'ES2014a', 'ES2013c', 'metadata', 'ES2013d', 'ES2016d', 'ES2013a', 'ES2015d', 'ES2015a', 'ES2015c', 'ES2015b', 'ES2013b', 'ES2016c', 'ES2014c']
31001.213968253967
{'ES2016b': 2412.224036281179, 'ES2016a': 1384.189387755102, 'ES2014b': 2319.8933786848074, 'ES2014d': 2911.36, 'ES2014a': 1149.0133786848073, 'ES2013c': 2358.1227210884354, 'ES2013d': 1898.56, 'ES2016d': 1523.2533786848073, 'ES2013a': 825.1733786848073, 'ES2015d': 1931.5627210884354, 'ES2015a': 1146.56, 'ES2015c': 2135.8933786848074, 'ES2015b': 2294.85873015873, 'ES2013b': 2128.629387755102, 'ES2016c': 2308.394693877551, 'ES2014c': 2273.525396825397}
1937.575873015873

In [25]:
total_seconds = avg_dur
hours = total_seconds // 3600
minutes = (total_seconds % 3600) // 60
seconds = total_seconds % 60
time = '%02d:%02d:%02d'%(hours, minutes, seconds)
print(time)

00:32:17

In [26]:
total_seconds = total_dur
hours = total_seconds // 3600
minutes = (total_seconds % 3600) // 60
seconds = total_seconds % 60
time = '%02d:%02d:%02d'%(hours, minutes, seconds)
print(time)

08:36:41

# Create the full metadata file for AMI Meeting Corpus
It should contain the entire meeting transcript in a single string. So concatenate the individual segments from the transcript metadata csv and add to the meeting metadata csv file at the meeting_id row.

In [44]:
speaker_map = speaker_map.drop_duplicates(subset=['meeting_id'], ignore_index=True)

In [47]:
print(speaker_map)

    meeting_id
0      IS1000a
1      IS1000b
2      IS1000c
3      IS1000d
4      IS1001a
..         ...
166    EN2006a
167    EN2006b
168    EN2009b
169    EN2009c
170    EN2009d

[171 rows x 1 columns]

In [49]:
segment_df = pd.read_csv('/root/master_thesis/thesis_multi_speaker_asr/data/amicorpus/metadata.csv')
meet_df = pd.read_csv('/root/master_thesis/thesis_multi_speaker_asr/data/amicorpus/meeting_metadata.csv')

segment_df = segment_df.groupby('meeting_id').apply(lambda x: x.sort_values('start'))
segment_df = segment_df.groupby('meeting_id')['text'].apply(lambda x: x.sum()).reset_index()
print(segment_df)

final_df = speaker_map.merge(
    segment_df,
    how='right',
    on='meeting_id'
)
final_df.head(20)

   meeting_id                                               text
0     ES2014a  Right , sostart of the first meeting . Uh .Mm-...
1     ES2014b  Right uh .So um .So where's the PowerPoint pre...
2     ES2014c  Okay .Right .Conceptual design meeting . Right...
3     ES2014d  So is Why not save that .No , you'll ha have t...
4     ES2015a  Alright , that did nothing . Okay . Welcome to...
5     ES2015b  Okay .Yeah . That's okay . That's okay .Okay ....
6     ES2015c  Is everyone ready to start ? Okay . Great . We...
7     ES2015d  Okay . Here we go .Alright , the agenda for th...
8     ES2016a  Okay . Oh , that's not gonna work .Oh , alrigh...
9     ES2016b  Oh .DuOkay .Hm .Thanks for coming to this meet...
10    ES2016c  Okay ..Right .Okay .Alright . Is everyone here...
11    ES2016d  Yep . Soon as Iget this .Okay . This is our la...

   meeting_id                                               text
0     ES2014a  Right , sostart of the first meeting . Uh .Mm-...
1     ES2014b  Right uh .So um .So where's the PowerPoint pre...
2     ES2014c  Okay .Right .Conceptual design meeting . Right...
3     ES2014d  So is Why not save that .No , you'll ha have t...
4     ES2015a  Alright , that did nothing . Okay . Welcome to...
5     ES2015b  Okay .Yeah . That's okay . That's okay .Okay ....
6     ES2015c  Is everyone ready to start ? Okay . Great . We...
7     ES2015d  Okay . Here we go .Alright , the agenda for th...
8     ES2016a  Okay . Oh , that's not gonna work .Oh , alrigh...
9     ES2016b  Oh .DuOkay .Hm .Thanks for coming to this meet...
10    ES2016c  Okay ..Right .Okay .Alright . Is everyone here...
11    ES2016d  Yep . Soon as Iget this .Okay . This is our la...

In [50]:
final_df.to_csv('/root/master_thesis/thesis_multi_speaker_asr/data/amicorpus/metadata_3.csv', index=False)